[package]
name = "linked_html_compiler"
version = "0.1.0"
edition = "2021"
authors = ["KiY"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
